# Site settings
title: syncopated studios
logo: /assets/images/site_header02.png
description: >
  experiences and experiments in the pursuit of optimal enjoyment

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://syncopatedstudios.github.io" # the base hostname & protocol for your site

author:
  fullname: Robert Pannick
  googleplus:
  github: b08x
  twitter:
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting

# Handling Reading
exclude: ["README.md", "README.html", "Gemfile", "Gemfile.lock", "resources/*", "_drafts/*", "_mdwriter.cson"]

# Build settings
highlighter: null
markdown: kramdown

plugins:
  - jekyll-diagrams

jekyll-diagrams:
  font: "Hack Nerd Font"
  size: 320x240
  antialias: true

sass:
    sass_dir: _sass
#plugins:
  # - jekyll-assets
  # - jekyll-transform

# assets:
#   source_maps: true
#   destination: "/assets"
#   compression: false
#   gzip: false
#   defaults:
#     integrity:
#       {css,img,js}: false
#   caching:
#     enabled: true
#     path: ".jekyll-cache/assets"
#     type: file
#   # --
#   # Assets you wish to always have compiled.
#   #   This can also be combined with raw_precompile which
#   #   copies assets without running through the pipeline
#   #   making them ultra fast.
#   # --
#   precompile: []
#   raw_precompile: [
#     #
#   ]
#   # --
#   # baseurl: whether or not to append site.baseurl
#   # destination: the folder you store them in on the CDN.
#   # url: the CDN url (fqdn, or w/ identifier).
#   # --
#   cdn:
#     baseurl: false
#     destination: false
#     url: null
#   # --
#   # See lib/jekyll/assets/config.rb
#   #   for a list of defaults
#   # --
#   sources:
#     - _assets/css
#     - _assets/images
#     - _assets/vendor
#   plugins:
#     css: { autoprefixer: {}}
#     img: { optim: {}}

# transform:
#   folder: '_wiki'
#   page_yaml:
#     layout: page
#   post_yaml:
#     layout: page
